// Mocks generated by Mockito 5.4.6 from annotations
// in myapp/test/widgets/main_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:cloud_firestore/cloud_firestore.dart' as _i4;
import 'package:firebase_auth/firebase_auth.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:myapp/services/auth_service.dart' as _i5;
import 'package:myapp/services/user_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [UserService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserService extends _i1.Mock implements _i2.UserService {
  MockUserService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i4.DocumentSnapshot<Map<String, dynamic>>> getUserStream(
    String? uid,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserStream, [uid]),
            returnValue:
                _i3.Stream<_i4.DocumentSnapshot<Map<String, dynamic>>>.empty(),
          )
          as _i3.Stream<_i4.DocumentSnapshot<Map<String, dynamic>>>);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i5.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i6.User?> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i3.Stream<_i6.User?>.empty(),
          )
          as _i3.Stream<_i6.User?>);

  @override
  _i3.Future<_i6.User?> signInWithEmailAndPassword(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmailAndPassword, [email, password]),
            returnValue: _i3.Future<_i6.User?>.value(),
          )
          as _i3.Future<_i6.User?>);

  @override
  _i3.Future<_i6.User?> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i3.Future<_i6.User?>.value(),
          )
          as _i3.Future<_i6.User?>);

  @override
  _i3.Future<_i6.User?> registerWithEmailAndPassword(
    String? email,
    String? password,
    String? displayName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#registerWithEmailAndPassword, [
              email,
              password,
              displayName,
            ]),
            returnValue: _i3.Future<_i6.User?>.value(),
          )
          as _i3.Future<_i6.User?>);

  @override
  _i3.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
