// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_development.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtqDIORJAVB5kaNZRKNuEEAJ5gqyH3Vm8',
    appId: '1:707974722454:web:e02711bc06fb039aa7e3b7',
    messagingSenderId: '707974722454',
    projectId: 'apiclientapp',
    authDomain: 'apiclientapp.firebaseapp.com',
    storageBucket: 'apiclientapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPFgTPcpmhpMvJlGrxkb4sUdPScEZQWAU',
    appId: '1:707974722454:android:a8aae63809100940a7e3b7',
    messagingSenderId: '707974722454',
    projectId: 'apiclientapp',
    storageBucket: 'apiclientapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvQZvQZvQZvQZvQZvQZvQZvQZvQZvQZvQ',
    appId: '1:987654321:ios:fedcba987654321',
    messagingSenderId: '987654321',
    projectId: 'apiclientapp',
    storageBucket: 'apiclientapp.appspot.com',
    databaseURL: 'https://apiclientapp-default-rtdb.firebaseio.com',
    iosBundleId: 'com.example.sessionizer.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvQZvQZvQZvQZvQZvQZvQZvQZvQZvQZvQ',
    appId: '1:987654321:ios:fedcba987654321',
    messagingSenderId: '987654321',
    projectId: 'apiclientapp',
    storageBucket: 'apiclientapp.appspot.com',
    databaseURL: 'https://apiclientapp-default-rtdb.firebaseio.com',
    iosBundleId: 'com.example.sessionizer.dev',
  );
}
